admin_email: info@admin.com
admin_password: admin
admin_user: admin
allow_reports: false
base_path: ""
cleanup_interval: 1h0m0s
cmd_file: /bin/bash
db_conn: postgres
db_database: statping
db_host: localhost
db_port: 5432
db_user: statping
description: This is an awesome page
disable_logs: false
domain: localhost:8080
go_env: ""
is_aws: false
is_docker: false
max_idle_conn: 25
max_life_conn: 5m0s
max_open_conn: 25
name: Demo
postgres_sslmode: disable
remove_after: 2160h0m0s
sample_data: true
sass: /usr/local/bin/sass
statping_dir: /Users/ankitgupta
use_assets: false
use_cdn: true
version: ""